### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by handsomeman1** [iamaziz/ar-embeddings#2]
Hello, can you send me  dependencies file that you have configured？
gensim==1.0.1
matplotlib==2.0.0
nltk==3.2.2
numpy==1.12.1
pandas==0.19.2
scikit_learn==0.18.1
I didn't find the library file.   My email address is  lingchen1110@126.com.   thank you

**Comment by iamaziz** [comment]
Hey you can download it from [here](https://raw.githubusercontent.com/iamaziz/ar-embeddings/master/requirements.txt). And to install the dependencies run:
`$ pip install -r requirements.txt`
